# Generated by Django 4.2.21 on 2025-05-26 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('feliz', 'Feliz'), ('triste', 'Triste'), ('ansioso', 'Ansioso'), ('calmo', 'Calmo'), ('irritado', 'Irritado'), ('grato', 'Grato')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
