# Generated by Django 4.2.21 on 2025-05-26 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_remove_dailyentry_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
